export const CATEGORIES = [
  { id: 'general', name: 'General Discussion', icon: '💬', description: 'General talk about campus life and more.' },
  { id: 'projects', name: 'In-house Projects', icon: '🛠️', description: 'Showcase and collaborate on student projects.' },
  { id: 'internships', name: 'Internships', icon: '💼', description: 'Opportunities and advice for internships.' },
  { id: 'placements', name: 'Placements', icon: '🚀', description: 'Placement prep and alumni experiences.' },
  { id: 'work-requests', name: 'Work Requests', icon: '🤝', description: 'Out-of-domain help for your projects.' },
  { id: 'chit-chat', name: 'Chit Chat', icon: '☕', description: 'Casual conversations and networking.' },
];

export const RESOURCES = [
  { id: 'r1', title: 'Data Structures & Algorithms', type: 'course', description: 'Comprehensive guide to DSA for placements.', link: '#', tags: ['CS', 'Placement'] },
  { id: 'r2', title: 'Operating Systems Question Bank', type: 'question-bank', description: 'Curated list of OS questions for exams.', link: '#', tags: ['OS', 'Exam'] },
  { id: 'r3', title: 'Google Internship Experience', type: 'internship', description: 'A detailed report by an alumni on their internship.', link: '#', tags: ['Google', 'Internship'] },
  { id: 'r4', title: 'Full-time Software Engineer Roadmap', type: 'fte', description: 'Step-by-step guide to landing an FTE role.', link: '#', tags: ['Career', 'FTE'] },
];

export const EVENTS = [
  { id: 'e1', title: 'Alumni Meetup 2026', date: '2026-04-15', type: 'meetup' },
  { id: 'e2', title: 'System Design Workshop', date: '2026-03-25', type: 'workshop' },
  { id: 'e3', title: 'Career Path Webinar', date: '2026-03-22', type: 'webinar' },
];

export const INITIAL_POSTS = [
  {
    id: '1',
    category: 'placements',
    author: 'alumni_sarah',
    authorRole: 'alumni',
    title: 'My journey from campus to Senior Engineer at Microsoft',
    content: 'I graduated in 2018. Here are the 5 key things I wish I knew before my first placement interview...',
    votes: 450,
    commentCount: 24,
    timestamp: '2 hours ago',
    userVote: null,
    hotScore: 95,
    newScore: 10,
    topScore: 80,
    risingScore: 60,
    comments: [
      {
        id: 'c1',
        author: 'student_rahul',
        content: 'This is so helpful! What resources did you use for system design?',
        timestamp: '1 hour ago',
        votes: 15,
        replies: [],
      },
    ],
  },
  {
    id: '2',
    category: 'projects',
    author: 'student_dev',
    authorRole: 'student',
    title: 'Looking for collaborators for an AI-based campus navigation app',
    content: 'We are building a React Native app that uses AR for indoor navigation. Need help with the backend (Python/FastAPI).',
    isWorkRequest: true,
    votes: 85,
    commentCount: 12,
    timestamp: '5 hours ago',
    userVote: null,
    hotScore: 88,
    newScore: 5,
    topScore: 75,
    risingScore: 45,
    comments: [],
  },
  {
    id: '3',
    category: 'internships',
    author: 'alumni_john',
    authorRole: 'alumni',
    title: 'Referrals available for Summer 2026 Internships at Amazon',
    content: 'If you have a strong background in Java and a good GPA, feel free to reach out with your resume.',
    pingAlumni: true,
    votes: 1200,
    commentCount: 85,
    timestamp: '8 hours ago',
    userVote: null,
    hotScore: 99,
    newScore: 2,
    topScore: 95,
    risingScore: 80,
    comments: [],
  },
  {
    id: '4',
    category: 'general',
    author: 'student_priya',
    authorRole: 'student',
    title: 'How to balance academics and open source contributions?',
    content: 'I am finding it hard to manage my time. Any tips from seniors or alumni?',
    votes: 150,
    commentCount: 30,
    timestamp: '12 hours ago',
    userVote: null,
    hotScore: 80,
    newScore: 1,
    topScore: 60,
    risingScore: 30,
    comments: [],
  },
];