const makeComment = (id, author, content, timestamp, votes = 0, replies = []) => ({
  id,
  author,
  content,
  timestamp,
  votes,
  replies,
});

const makeThread = ({
  id,
  title,
  excerpt,
  content,
  author,
  authorRole,
  createdAt,
  views,
  replies,
  likes,
  tags,
  attachments = [],
  isPinned = false,
  isSolved = false,
  comments = [],
}) => ({
  id,
  title,
  excerpt,
  content,
  author,
  authorRole,
  createdAt,
  views,
  replies,
  likes,
  tags,
  attachments,
  isPinned,
  isSolved,
  comments,
});

const placementComments = [
  makeComment(
    'c-placements-1',
    'student_rahul',
    'This is exactly what I needed. Did your prep change between aptitude and HR rounds?',
    '1 hour ago',
    12,
    [makeComment('c-placements-1-1', 'alumni_sara', 'I focused more on storytelling in HR rounds and kept examples from campus projects ready.', '45 minutes ago', 5)],
  ),
  makeComment('c-placements-2', 'alumni_isha', 'Sharing the mock interview checklist I used during final year.', '2 hours ago', 8),
];

export const CURRENT_USER = {
  id: 'user-current',
  name: 'Aarav Mehta',
  role: 'student',
  branch: 'CSE',
  year: 'Final Year',
  avatar: 'AM',
  isOnline: true,
};

export const FORUMS = [
  {
    id: 'placements',
    name: 'Placements & Careers',
    icon: '🚀',
    description: 'Interview prep, referral updates, offer stories, and career planning.',
    color: 'from-orange-500 via-amber-500 to-rose-500',
    members: 12840,
    activeNow: 38,
    threadCount: 286,
    subforumCount: 4,
    featured: true,
    subforums: [
      {
        id: 'mock-interviews',
        name: 'Mock Interviews',
        description: 'Practice rounds, feedback templates, and question banks.',
        threadCount: 42,
        activeNow: 9,
        tags: ['Prep', 'Feedback'],
        moderator: 'alumni_sara',
        threads: [
          makeThread({
            id: 't-placement-1',
            title: 'What actually helped in final round interviews?',
            excerpt: 'A breakdown of the prep routine that made the biggest difference.',
            content:
              'I stopped chasing every resource and focused on 3 things: core DSA patterns, project storytelling, and mock interviews with honest feedback. That shift helped me stay calm and explain tradeoffs clearly.',
            author: 'alumni_sara',
            authorRole: 'alumni',
            createdAt: '2 hours ago',
            views: 1240,
            replies: 18,
            likes: 154,
            tags: ['Interview', 'Prep'],
            isPinned: true,
            comments: placementComments,
          }),
          makeThread({
            id: 't-placement-2',
            title: 'How do you keep a revision sheet for aptitude?',
            excerpt: 'Trying to keep all formulas and shortcuts in one place.',
            content: 'I want a clean revision system for percentage, probability, and data interpretation. What format worked best for you?',
            author: 'student_priya',
            authorRole: 'student',
            createdAt: '5 hours ago',
            views: 431,
            replies: 6,
            likes: 42,
            tags: ['Aptitude', 'Study System'],
          }),
        ],
      },
      {
        id: 'referral-desk',
        name: 'Referral Desk',
        description: 'Referral etiquette, company insights, and hiring windows.',
        threadCount: 58,
        activeNow: 14,
        tags: ['Referrals', 'Companies'],
        moderator: 'alumni_john',
        threads: [
          makeThread({
            id: 't-placement-3',
            title: 'Amazon referrals open for summer internships',
            excerpt: 'Eligibility notes and the resume format I am asking for.',
            content:
              'Sharing a limited window for summer internship referrals. Looking for students with strong Java or backend projects and a clear GitHub footprint.',
            author: 'alumni_john',
            authorRole: 'alumni',
            createdAt: '8 hours ago',
            views: 2201,
            replies: 31,
            likes: 261,
            tags: ['Referral', 'Internship'],
          }),
        ],
      },
      {
        id: 'offer-stories',
        name: 'Offer Stories',
        description: 'Offer breakdowns, salary discussions, and negotiation notes.',
        threadCount: 36,
        activeNow: 7,
        tags: ['Offers', 'Career Stories'],
        moderator: 'career_cell',
        threads: [
          makeThread({
            id: 't-placement-4',
            title: 'How I negotiated my first offer without sounding aggressive',
            excerpt: 'A practical script and timing advice.',
            content: 'I kept the conversation grounded in market research and my other interview timelines. The key was asking for room to compare with the broader role scope.',
            author: 'alumni_ritika',
            authorRole: 'alumni',
            createdAt: '1 day ago',
            views: 860,
            replies: 15,
            likes: 91,
            tags: ['Negotiation', 'Offer'],
          }),
        ],
      },
      {
        id: 'company-pings',
        name: 'Company Pings',
        description: 'Drive posts, timelines, and role-specific updates.',
        threadCount: 52,
        activeNow: 8,
        tags: ['Hiring', 'Updates'],
        moderator: 'placement_team',
        threads: [],
      },
    ],
  },
  {
    id: 'academics',
    name: 'Academics & Subjects',
    icon: '📚',
    description: 'Class notes, subject guidance, exam prep, and lab support.',
    color: 'from-sky-500 via-blue-500 to-indigo-500',
    members: 8420,
    activeNow: 25,
    threadCount: 194,
    subforumCount: 4,
    featured: true,
    subforums: [
      {
        id: 'data-structures',
        name: 'Data Structures',
        description: 'Problems, revision notes, and professor-approved examples.',
        threadCount: 48,
        activeNow: 11,
        tags: ['DSA', 'Revision'],
        moderator: 'prof_kanhaiya',
        threads: [
          makeThread({
            id: 't-academics-1',
            title: 'Best way to revise trees before the internals?',
            excerpt: 'Need a compact plan for the next three days.',
            content: 'I am trying to revise trees and hash maps quickly. I would like a sequence that balances theory, implementation, and practice problems.',
            author: 'student_neha',
            authorRole: 'student',
            createdAt: '3 hours ago',
            views: 602,
            replies: 9,
            likes: 48,
            tags: ['Exam', 'Trees'],
          }),
        ],
      },
      {
        id: 'os-lab',
        name: 'OS Lab Support',
        description: 'Deadlocks, scheduling, and viva preparation.',
        threadCount: 33,
        activeNow: 6,
        tags: ['OS', 'Lab'],
        moderator: 'lab_incharge',
        threads: [
          makeThread({
            id: 't-academics-2',
            title: 'Need a clean explanation of page replacement algorithms',
            excerpt: 'Looking for notes that compare FIFO, LRU, and optimal.',
            content: 'Can someone share a short version of the algorithms that is easy to revise the night before the lab viva?',
            author: 'student_rohan',
            authorRole: 'student',
            createdAt: '9 hours ago',
            views: 390,
            replies: 4,
            likes: 31,
            tags: ['OS', 'Viva'],
          }),
        ],
      },
      {
        id: 'dbms-notes',
        name: 'DBMS Notes',
        description: 'Normalization, SQL practice, and short revision sheets.',
        threadCount: 29,
        activeNow: 5,
        tags: ['SQL', 'Notes'],
        moderator: 'teaching_assistant',
        threads: [],
      },
      {
        id: 'subject-resources',
        name: 'Subject Resources',
        description: 'Curated resources attached to each subject.',
        threadCount: 24,
        activeNow: 3,
        tags: ['Materials', 'Guides'],
        moderator: 'library_team',
        threads: [],
      },
    ],
  },
  {
    id: 'campus-life',
    name: 'Campus Life',
    icon: '🌿',
    description: 'Clubs, hostels, food, transport, events, and everyday campus stories.',
    color: 'from-emerald-500 via-teal-500 to-cyan-500',
    members: 6710,
    activeNow: 21,
    threadCount: 148,
    subforumCount: 4,
    featured: true,
    subforums: [
      {
        id: 'clubs-events',
        name: 'Clubs & Events',
        description: 'Announcements, meetups, and club recruitment threads.',
        threadCount: 44,
        activeNow: 10,
        tags: ['Events', 'Clubs'],
        moderator: 'student_union',
        threads: [],
      },
      {
        id: 'hostel-life',
        name: 'Hostel Life',
        description: 'Room tips, mess reviews, and living arrangements.',
        threadCount: 31,
        activeNow: 7,
        tags: ['Hostel', 'Campus'],
        moderator: 'warden_office',
        threads: [],
      },
      {
        id: 'food-corners',
        name: 'Food Corners',
        description: 'Mess scores, canteen updates, and favorite food spots.',
        threadCount: 24,
        activeNow: 2,
        tags: ['Food', 'Reviews'],
        moderator: 'student_council',
        threads: [],
      },
      {
        id: 'transport-desk',
        name: 'Transport Desk',
        description: 'Buses, routes, and commute coordination.',
        threadCount: 19,
        activeNow: 2,
        tags: ['Transport', 'Routes'],
        moderator: 'admin_support',
        threads: [],
      },
    ],
  },
  {
    id: 'projects',
    name: 'Projects & Hackathons',
    icon: '🛠️',
    description: 'Collaborations, demos, open source, and product experiments.',
    color: 'from-violet-500 via-fuchsia-500 to-pink-500',
    members: 5140,
    activeNow: 17,
    threadCount: 133,
    subforumCount: 4,
    featured: true,
    subforums: [
      {
        id: 'team-up',
        name: 'Team Up',
        description: 'Find collaborators for projects, clubs, and hackathons.',
        threadCount: 37,
        activeNow: 8,
        tags: ['Collaboration', 'Hackathons'],
        moderator: 'hackathon_cell',
        threads: [
          makeThread({
            id: 't-projects-1',
            title: 'Looking for one backend dev for an indoor navigation app',
            excerpt: 'React Native frontend already in progress.',
            content:
              'We have a working prototype for campus navigation and need someone comfortable with Python/FastAPI and location APIs. The goal is to ship a student-friendly indoor map.',
            author: 'student_dev',
            authorRole: 'student',
            createdAt: '5 hours ago',
            views: 728,
            replies: 12,
            likes: 73,
            tags: ['Project', 'Hiring'],
            attachments: ['ui-wireframe.pdf'],
          }),
        ],
      },
      {
        id: 'showcase',
        name: 'Showcase',
        description: 'Project demos, feedback, and launch notes.',
        threadCount: 31,
        activeNow: 4,
        tags: ['Demo', 'Feedback'],
        moderator: 'design_club',
        threads: [],
      },
      {
        id: 'open-source',
        name: 'Open Source',
        description: 'Repos, issues, and contribution opportunities.',
        threadCount: 28,
        activeNow: 3,
        tags: ['GitHub', 'OSS'],
        moderator: 'oss_mentor',
        threads: [],
      },
      {
        id: 'startup-hub',
        name: 'Startup Hub',
        description: 'Build-in-public updates and product discussions.',
        threadCount: 27,
        activeNow: 2,
        tags: ['Startup', 'Product'],
        moderator: 'founder_circle',
        threads: [],
      },
    ],
  },
];

export const SUBJECTS = [
  {
    id: 'subj-dsa',
    name: 'Data Structures & Algorithms',
    year: 2,
    prof: 'Prof. K. Rao',
    author: 'library_team',
    attachments: ['dsa-revision.pdf', 'trees-practice-sheet.pdf'],
    resourceIds: ['res-dsa-1', 'res-dsa-2'],
  },
  {
    id: 'subj-os',
    name: 'Operating Systems',
    year: 3,
    prof: 'Prof. N. Menon',
    author: 'lab_incharge',
    attachments: ['os-viva-questions.pdf'],
    resourceIds: ['res-os-1'],
  },
  {
    id: 'subj-dbms',
    name: 'Database Management Systems',
    year: 3,
    prof: 'Prof. S. Iyer',
    author: 'teaching_assistant',
    attachments: ['sql-practice-set.pdf'],
    resourceIds: ['res-dbms-1'],
  },
];

export const RESOURCES = [
  {
    id: 'res-dsa-1',
    title: 'DSA Revision Vault',
    description: 'A structured set of notes, patterns, and problem solving templates.',
    fileUrl: '#',
    publicId: 'dsa-vault',
    fileType: 'pdf',
    fileSize: 1843200,
    thumbnailUrl: '',
    forum: 'academics',
    subjectId: 'subj-dsa',
  },
  {
    id: 'res-dsa-2',
    title: 'Trees and Graphs Practice Sheet',
    description: 'High-signal practice sheet for semester revision.',
    fileUrl: '#',
    publicId: 'trees-graphs',
    fileType: 'pdf',
    fileSize: 920000,
    thumbnailUrl: '',
    forum: 'academics',
    subjectId: 'subj-dsa',
  },
  {
    id: 'res-os-1',
    title: 'Operating Systems Viva Guide',
    description: 'Short answers for process scheduling, paging, and synchronization.',
    fileUrl: '#',
    publicId: 'os-viva',
    fileType: 'pdf',
    fileSize: 765000,
    thumbnailUrl: '',
    forum: 'academics',
    subjectId: 'subj-os',
  },
  {
    id: 'res-dbms-1',
    title: 'SQL Query Pattern Library',
    description: 'Common joins, grouping, and normalization examples.',
    fileUrl: '#',
    publicId: 'sql-patterns',
    fileType: 'doc',
    fileSize: 540000,
    thumbnailUrl: '',
    forum: 'academics',
    subjectId: 'subj-dbms',
  },
];

export const EVENTS = [
  { id: 'e1', title: 'Alumni Meetup 2026', date: '2026-04-15', type: 'meetup' },
  { id: 'e2', title: 'System Design Workshop', date: '2026-03-25', type: 'workshop' },
  { id: 'e3', title: 'Career Path Webinar', date: '2026-03-22', type: 'webinar' },
];

export const MESSAGES = [
  {
    id: 'm1',
    sender: { id: 'alumni_sara', name: 'Sara', role: 'alumni' },
    receiver: { id: 'user-current', name: 'Aarav Mehta', role: 'student' },
    content: 'I can review your resume if you share the latest version.',
    conversationId: 'conv-placements-1',
    isRead: false,
    createdAt: '15 minutes ago',
  },
  {
    id: 'm2',
    sender: { id: 'prof_kanhaiya', name: 'Prof. K. Rao', role: 'faculty' },
    receiver: { id: 'user-current', name: 'Aarav Mehta', role: 'student' },
    content: 'The exam resources are uploaded in the DSA subject board.',
    conversationId: 'conv-academics-1',
    isRead: true,
    createdAt: '2 hours ago',
  },
];

export const NOTIFICATIONS = [
  {
    id: 'n1',
    recipient: 'user-current',
    sender: 'placement_team',
    type: 'THREAD_MENTION',
    entityId: 't-placement-3',
    entityType: 'Thread',
    isRead: false,
    createdAt: '8 minutes ago',
  },
  {
    id: 'n2',
    recipient: 'user-current',
    sender: 'alumni_john',
    type: 'REPLY',
    entityId: 'c-placements-1',
    entityType: 'Comment',
    isRead: true,
    createdAt: '1 hour ago',
  },
];

export const REPORTS = [
  {
    id: 'rep-1',
    commentId: 'c-placements-2',
    reason: 'Spam',
    status: 'open',
  },
  {
    id: 'rep-2',
    commentId: 'c-academic-2',
    reason: 'Off-topic',
    status: 'resolved',
  },
];